# Generated by Django 5.0 on 2023-12-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWithProducts',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('delivery_mode', models.CharField(max_length=50)),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('total_price', models.FloatField()),
            ],
            options={
                'db_table': 'OrderWithProducts',
                'managed': False,
            },
        ),
    ]
